### ISSUE TITLE
Generic Repository ve Unit of Work 

### ISSUE THREAD

**Issue by murattdogan** [alirizaadiyahsi/Nucleus#105]
Generic Repository ve Unit of Work in  EF Core

**Comment by alirizaadiyahsi** [comment]
No plan to work with different DBs. So no need/plan to implement repository pattern. 
And unit of work is handling in action filter that named `UnitOfWorkFilter.cs`. 

Check this: 
https://github.com/alirizaadiyahsi/Nucleus/blob/dev/src/Nucleus.Web.Core/ActionFilters/UnitOfWorkFilter.cs
