### ISSUE TITLE
Add user

### ISSUE THREAD

**Issue by alirizaadiyahsi** [alirizaadiyahsi/Nucleus#13]
Also add roles to user

**Comment by MuratGundes** [comment]
Hi,

I can take this one if you want ?

**Comment by alirizaadiyahsi** [comment]
Ofcourse, always! It would be very appreciated!  I checked your PR but I changed project structure completely. So there are a lot of conflicts. 

If you still want to send PR, it would be great. Thanks

**Comment by MuratGundes** [comment]
Thank you for your comment Ali Rıza. Actually I'm new in contribution and still learning Vue.js.
I developed before your changing and I didn't recognize the project was changed. I saw your review and it was really helpful for me. Please feel free for code review and comment, thank you 👍
