### ISSUE TITLE
vue project always we must run 

### ISSUE THREAD

**Issue by yasiaydi** [alirizaadiyahsi/Nucleus#90]
Always we must run vue project by `yarn serve` command. You can automatized this command operations

**Comment by alirizaadiyahsi** [comment]
What do you mean by `your can automatized this command operations`. 
Could you give more detail?

**Comment by yasiaydi** [comment]
i want to say 
 Execute yarn serve command automatically after vue project run

**Comment by yzorg** [comment]
@alirizaadiyahsi I could take this task this weekend.  I believe there's a "command runner" Visual Studio extension that supports npm & Yarn scripts at startup.  Does this project take contributions (PRs)?

**Comment by alirizaadiyahsi** [comment]
> Does this project take contributions (PRs)?

Of course. Always!
